### PR TITLE
[WIP] Fix namespace issues in examples

### LINKED ISSUE #28: examples/p5ab-hairpin broken
`python generate-figure.py` generates the following error:

```
output model:
--------------------------------------------------------------------------------
GaussianOutputModel
nstates: 3
means: [ 13.84940002  12.54858602  13.01613252]
sigmas: [ 0.21264276  0.20973714  0.2004431 ]
--------------------------------------------------------------------------------

14:50:12 INFO BHMM: Elapsed time for Baum-Welch solution: 3.651 s
14:50:12 INFO BHMM: Computing Viterbi path:
14:50:12 INFO BHMM: Elapsed time for Viterbi path computation: 0.010 s
14:50:12 INFO BHMM: =================================================================
Initializing BHMM and running with 100 samples.
Traceback (most recent call last):
  File "generate-figure.py", line 86, in <module>
    run(args.nstates, args.nsamples)
  File "generate-figure.py", line 53, in run
    sampler = bhmm.BayesianHMMSampler(O, nstates, initial_model=mle)
AttributeError: 'module' object has no attribute 'BayesianHMMSampler'
```

This example is needed for the paper, so we need this one to work.

### PR DESCRIPTION
**Pull request by jchodera**
Starting to fix namespace issues caused by https://github.com/bhmm/bhmm/commit/4163825402a4520c83828a53cc44464f0054d642 to fix #28.

### CODE REVIEW

**Comment by jchodera** [comment]
Closing because I don't know how to fix things.
